"""Added Foreign Key

Revision ID: 226930f9a054
Revises: ccb956156b6a
Create Date: 2023-05-13 18:34:27.879310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226930f9a054'
down_revision = 'ccb956156b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['poster_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
