"""replaced favorite_color with program

Revision ID: 43b2e20f3384
Revises: e815187ef08a
Create Date: 2023-05-14 15:41:04.486910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43b2e20f3384'
down_revision = 'e815187ef08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.String(length=120), nullable=True))
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', mysql.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('program')

    # ### end Alembic commands ###
