"""added file_attachment

Revision ID: 502991642a45
Revises: e1f1bb4b8b14
Create Date: 2023-05-15 13:21:14.663945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502991642a45'
down_revision = 'e1f1bb4b8b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_attachment', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('file_attachment')

    # ### end Alembic commands ###
