"""changed slug to document type

Revision ID: e1f1bb4b8b14
Revises: 43b2e20f3384
Create Date: 2023-05-15 11:07:58.123367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1f1bb4b8b14'
down_revision = '43b2e20f3384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_type', sa.String(length=255), nullable=True))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('doc_type')

    # ### end Alembic commands ###
